# Generated by Django 6.1.2 on 2026-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
