# Generated by Django 6.1.2 on 2026-10-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
